### ISSUE TITLE
Issue while Converting Word to HTML

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#101]
not able to convert word doc to HTML due to below reason.

```
08:20:36.013 [main] INFO  o.d.openpackaging.io.SaveToZipFile - ...Done!
08:20:39.868 [main] INFO  c.h.y.f.impl.doc.connector.OOServer - OOServer is killing office instance with port 6557
08:20:39.953 [main] INFO  c.h.y.f.i.d.c.WinProcessManager - Windows office process manager is going to kill following processes [0]
08:20:39.968 [main] WARN  c.h.y.f.i.xls.DocumentConverterImpl - An error occurred while converting. System will retry to generate report again.
java.lang.RuntimeException: com.haulmont.yarg.exception.ReportingException: An error occurred while running task in Open Office server
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeIntegration.runTaskWithTimeout(OfficeIntegration.java:96)
	at com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl.convertOnes(DocumentConverterImpl.java:91)
	at com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl.convertWithRetry(DocumentConverterImpl.java:59)
	at com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl.convertToHtml(DocumentConverterImpl.java:54)
	at com.haulmont.yarg.formatters.impl.DocxFormatter.saveAndClose(DocxFormatter.java:159)
	at com.haulmont.yarg.formatters.impl.DocxFormatter.renderDocument(DocxFormatter.java:93)
	at com.haulmont.yarg.reporting.Reporting.generateReport(Reporting.java:133)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:100)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:77)
	at com.yarg.YargWord.testInvoiceReportRaw(YargWord.java:84)
	at com.yarg.YargWord.main(YargWord.java:24)
Caused by: com.haulmont.yarg.exception.ReportingException: An error occurred while running task in Open Office server
	at com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl.lambda$convertOnes$0(DocumentConverterImpl.java:88)
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeIntegration.lambda$runTaskWithTimeout$0(OfficeIntegration.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.star.task.ErrorCodeIOException: 
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:182)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:148)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:344)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:313)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:101)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:652)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:154)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:136)
	at com.sun.proxy.$Proxy45.storeToURL(Unknown Source)
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeResourceProvider.saveXComponent(OfficeResourceProvider.java:140)
	at com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl.saveAndClose(DocumentConverterImpl.java:96)
	at com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl.lambda$convertOnes$0(DocumentConverterImpl.java:86)
	... 5 common frames omitted
08:20:42.809 [main] INFO  c.h.y.f.impl.doc.connector.OOServer - OOServer is killing office instance with port 6558
08:20:42.876 [main] INFO  c.h.y.f.i.d.c.WinProcessManager - Windows office process manager is going to kill following processes [0]
```

Can any one help me

**Comment by srinivas460** [comment]
Can any one help me
