### ISSUE TITLE
Error while generation report with more than 65535 rows

### ISSUE THREAD

**Issue by PavelPimKot** [cuba-platform/yarg#172]
### Environment

- YARG version:  <1.0.33>
- Browser: <Chrome>
- Database: <PostgreSQL>
- Operating system: <Linux>

### Description of the bug or enhancement
Generation report with more than  65535 rows.
Caused by: java.lang.IllegalArgumentException: Invalid row number (65536) outside allowable range (0..65535)
	at org.apache.poi.hssf.usermodel.HSSFRow.setRowNum(HSSFRow.java:239) ~[poi-3.9.20130515.jar:3.9]
	at org.apache.poi.hssf.usermodel.HSSFRow.<init>(HSSFRow.java:87) ~[poi-3.9.20130515.jar:3.9]
	at org.apache.poi.hssf.usermodel.HSSFRow.<init>(HSSFRow.java:71) ~[poi-3.9.20130515.jar:3.9]
	at org.apache.poi.hssf.usermodel.HSSFSheet.createRow(HSSFSheet.java:232) ~[poi-3.9.20130515.jar:3.9]
	at com.haulmont.yarg.formatters.impl.XLSFormatter.writeHorizontalBand(XLSFormatter.java:312) ~[yarg-1.0.33.jar:?]
	at com.haulmont.yarg.formatters.impl.XLSFormatter.writeBand(XLSFormatter.java:258) ~[yarg-1.0.33.jar:?]
	at com.haulmont.yarg.formatters.impl.XLSFormatter.processDocument(XLSFormatter.java:148) ~[yarg-1.0.33.jar:?]
	at com.haulmont.yarg.formatters.impl.XLSFormatter.renderDocument(XLSFormatter.java:117) ~[yarg-1.0.33.jar:?]
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:128) ~[yarg-1.0.33.jar:?]
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:80) ~[yarg-1.0.33.jar:?]
	
As i know, main issue is that Exel version is older than version of 2010, and it suuport only 65536 rows, should i upgrade YARG version? Maybe some version uses Exel version thath younger than 2010 ?

**Comment by gorbunkov** [comment]
As far as I know  65535 rows count is a limitation of .XLS format. You may use .xlsx format.
