### ISSUE TITLE
Caused by: com.haulmont.yarg.exception.DataLoadingException: An error occurred while loading data for data set

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#19]
getting this error while exporting a report of over 1500 record of table to pdf using word as template 

com.haulmont.yarg.exception.DataLoadingException: An error occurred while loading data for band [Items] and query [Items]. Report name []
	at com.haulmont.yarg.reporting.DataExtractorImpl.getQueryData(DataExtractorImpl.java:189)
	at com.haulmont.yarg.reporting.DataExtractorImpl.getQueriesResult(DataExtractorImpl.java:140)
	at com.haulmont.yarg.reporting.DataExtractorImpl.getBandData(DataExtractorImpl.java:105)
	at com.haulmont.yarg.reporting.DataExtractorImpl.createBands(DataExtractorImpl.java:76)
	at com.haulmont.yarg.reporting.DataExtractorImpl.extractData(DataExtractorImpl.java:60)
	at com.haulmont.yarg.reporting.Reporting.loadBandData(Reporting.java:143)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:103)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:82)
Caused by: com.haulmont.yarg.exception.DataLoadingException: An error occurred while loading data for data set [Items]
	at com.haulmont.yarg.loaders.impl.GroovyDataLoader.loadData(GroovyDataLoader.java:52)
	at com.haulmont.yarg.reporting.DataExtractorImpl.getQueryData(DataExtractorImpl.java:185)
	... 9 more
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during class generation: Method code too large!

**Comment by tinhol** [comment]
Hello.

Do you get the same error when you export, for instance,10 records?

**Comment by srinivas460** [comment]
Nope , i get this error if records > 950

**Comment by tinhol** [comment]
Could you please provide the Groovy script, so we can analyze it?

**Comment by srinivas460** [comment]
how to get the Groovy Script as i am using YARG in JAVA  to export .

**Comment by tinhol** [comment]
As I see from the exception you are using GroovyDataLoader. So if you use XML description of the report - please attach the XML file. If you create the report programmatically - please attach the code for report creation.

Thank you.
