### ISSUE TITLE
 An error occurred while running task in Open Office server

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#30]
Getting the below error : 
> java.lang.RuntimeException: com.haulmont.yarg.exception.ReportingException: An error occurred while running task in Open Office server

when i try to do the process of Excel template to Pdf output in linux server , it works fine in Windows but not in linux server. i tried with OpenOffice and LibreOffice

**Comment by andreysubbotin** [comment]
Hi @srinivas460 

I tried to reproduce the problem on Ubuntu. Conversation from Excel to PDF using Open Office works correctly without errors.

Could you provide sample application and sample report for the test case?

Thanks.

**Comment by srinivas460** [comment]
i am still facing the same below is the error i face..

Sample is simple just 2 column of sample data and using the template to export to pdf .. 
and my path in linux is : /usr/bin/openoffice4
**Error Log below :**

**java.lang.RuntimeException: java.lang.RuntimeException: com.haulmont.yarg.exception.OpenOfficeException: Unable to create Open office components.**

**Caused by: com.haulmont.yarg.exception.OpenOfficeException: Unable to create Open office components.**
        at com.haulmont.yarg.formatters.impl.doc.connector.OfficeConnection.open(OfficeConnection.java:78) ~[yarg-1.0.70.jar:na]
        at com.haulmont.yarg.formatters.impl.doc.connector.OfficeIntegration$1.call(OfficeIntegration.java:81) ~[yarg-1.0.70.jar:na]
        at com.haulmont.yarg.formatters.impl.doc.connector.OfficeIntegration$1.call(OfficeIntegration.java:78) ~[yarg-1.0.70.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_60]
        ... 1 common frames omitted

**Caused by: com.sun.star.comp.helper.BootstrapException: null**
        at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapConnector.connect(BootstrapConnector.java:131) ~[yarg-1.0.70.jar:na]
        at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapSocketConnector.connect(BootstrapSocketConnector.java:48) ~[yarg-1.0.70.jar:na]
        at com.haulmont.yarg.formatters.impl.doc.connector.OfficeConnection.open(OfficeConnection.java:60) ~[yarg-1.0.70.jar:na]
        ... 6 common frames omitted

**Comment by tinhol** [comment]
Have you tried to put Open Office jars to your classpath? In YARG dependencies there are jars for Open Office 3.0, which can fail to connect to modern versions of Open/Libre Office.
`
compile(group: 'org.openoffice', name: 'juh', version: '3.0.0')

compile(group: 'org.openoffice', name: 'ridl', version: '3.0.0')

compile(group: 'org.openoffice', name: 'unoil', version: '3.0.0')
`

You need just to replace the above jars in your classpath with jars from your Open Office. Usually the jars are in /usr/share/libreoffice/program/classes or /usr/share/openiffice/program/classes directories.
