### ISSUE TITLE
Not able to Convert Html to Pdf .

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#41]
Hi ,

i am trying to convert HTML to PDF with page-break as i need every group in new page in pdf. but html to pdf is not working getting below error .

`Caused by: org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TrAX transformer). org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.
	at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.transform(XMLResource.java:222) ~[flying-saucer-core-9.1.7.jar:na]
	at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:181) ~[flying-saucer-core-9.1.7.jar:na]
	at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:80) ~[flying-saucer-core-9.1.7.jar:na]
	at org.xhtmlrenderer.swing.NaiveUserAgent.getXMLResource(NaiveUserAgent.java:286) ~[flying-saucer-core-9.1.7.jar:na]
	at org.xhtmlrenderer.pdf.ITextRenderer.loadDocument(ITextRenderer.java:148) ~[flying-saucer-pdf-9.1.7.jar:na]
	at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:152) ~[flying-saucer-pdf-9.1.7.jar:na]
	at com.haulmont.yarg.formatters.impl.HtmlFormatter.renderPdfDocument(HtmlFormatter.java:103) ~[yarg-2.0.11.jar:na]`

below is My HTML code:
`<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
			<title>Untitled Document</title>
		</head>

		<body>
			<div style="margin: 0px auto;">

				<div style="float: left; width: 100%;">
					<div class="details-div">
						<#assign params = Root.bands.Header>
								<#list params as Hname>
											<table border="0" cellpadding="0" cellspacing="0" class="report-table-details">

												<tr>
													<th scope="col">Name</th>
													<th scope="col">${Hname.fields.COL0}</th>
												</tr>	

													<tr>
																<th> CUTOMER SEGMENT</th>
																<th> QUANTITY </th>
																<th> UNIT PRICE</th>
																<th> TOTAL</th>
															</tr>
													<#list Hname.bands.Data as data>
													<tr>
															<td nowrap=true> ${data.fields.COL0} </td>
															<td nowrap=true> ${data.fields.COL1} </td>
															<td nowrap=true> ${data.fields.COL2} </td>
															<td nowrap=true> ${data.fields.COL3} </td>
													</tr>
													</#list>
											</table>
										</#list>
			</div>
	</body>
</html>
						`

please help me out .

**Comment by tinhol** [comment]
Hello.

It looks like your tempalte is not well formatter HTML/FTL file.

Please look at the [example](https://github.com/cuba-platform/yarg/blob/master/core/modules/core/test/smoketest/test.ftl)
